---
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/devdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  session:
    store-type: hash_map
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG